# -*- coding: utf-8 -*-
"""matplot_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-LNTDNFZ-Ow38361yTjhvE3sQ6l3Wzc
"""



"""### Exercise 1: Basic Line Plot
- **Task**: Create a line plot using the following data:
  ```python
  x = [1, 2, 3, 4, 5]
  y = [2, 4, 6, 8, 10]
  ```
  - Label the x-axis as **"X-Axis"** and the y-axis as **"Y-Axis"**.
  - Add a title: **"Simple Line Plot"**.
"""

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
# Create a line plot
plt.plot(x, y)

# Add labels and title
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Simple Line Plot')

# Display the plot
plt.show()

"""### Exercise 2: Bar Chart of Scores
- **Task**: Create a bar chart showing the scores of students:
  - **Categories**: `['Student A', 'Student B', 'Student C']`
  - **Values**: `[85, 90, 78]`
  - Label the x-axis as **"Students"** and the y-axis as **"Scores"**.
  - Add a title: **"Students' Scores"**.
"""

import matplotlib.pyplot as plt
categories = ['Student A', 'Student B', 'Student C']
values = [85, 90, 78]
plt.bar(categories, values)
plt.xlabel('Students')
plt.ylabel('Scores')
plt.title('Students Scores')
plt.show()

"""### Exercise 3: Scatter Plot of Heights vs Weights
- **Task**: Create a scatter plot using the following data:
  ```python
  heights = [150, 160, 170, 180, 190]
  weights = [50, 60, 65, 80, 85]
  ```
  - Label the x-axis as **"Heights"** and the y-axis as **"Weights"**.
  - Add a title: **"Heights vs Weights"**.
"""

import matplotlib.pyplot as plt
heights = [150, 160, 170, 180, 190]
weights = [50, 60, 65, 80, 85]
plt.scatter(heights,weights)
plt.xlabel('Heights')
plt.ylabel('Weights')
plt.title('Heights vs Weights')
plt.show()

"""### Exercise 4: Line Plot of Temperature Over Time
- **Task**: Create a line plot showing the change in temperature over time:
  ```python
  time = [1, 2, 3, 4, 5]
  temperature = [30, 32, 35, 33, 31]
  ```
  - Label the x-axis as **"Time"** and the y-axis as **"Temperature"**.
  - Add a title: **"Temperature Over Time"**.
"""

import matplotlib.pyplot as plt
time = [1, 2, 3, 4, 5]
temperature = [30, 32, 35, 33, 31]
plt.plot(time,temperature)
plt.xlabel('Time')
plt.ylabel('Tempreture')
plt.title('Temperature Over Time')
plt.show()

"""### Exercise 5: Bar Chart for Favorite Colors
- **Task**: Create a bar chart showing how many people like each color:
  - **Categories**: `['Red', 'Blue', 'Green', 'Yellow']`
  - **Values**: `[10, 20, 15, 5]`
  - Label the x-axis as **"Colors"** and the y-axis as **"Number of People"**.
  - Add a title: **"Favorite Colors"**.
"""

import matplotlib.pyplot as plt
Categories = ['Red', 'Blue', 'Green', 'Yellow']
Values = [10, 20, 15, 5]
plt.bar(Categories,Values)
plt.xlabel('Colors')
plt.ylabel('Number of People')
plt.title('Favorite Colors')
plt.show()

"""### Exercise 6: Scatter Plot of Age vs Height
- **Task**: Create a scatter plot using the following data:
  ```python
  age = [10, 12, 14, 16, 18]
  height = [140, 145, 150, 160, 170]
  ```
  - Label the x-axis as **"Age"** and the y-axis as **"Height"**.
  - Add a title: **"Age vs Height"**.
"""

import matplotlib.pyplot as plt
age = [10, 12, 14, 16, 18]
height = [140, 145, 150, 160, 170]
plt.scatter(age,height)
plt.xlabel('Age')
plt.ylabel('Height')
plt.title('Age vs Height')
plt.show()

"""### Exercise 7: Customizing Line Plot
- **Task**: Create a line plot using the following data:
  ```python
  x = [1, 2, 3, 4]
  y = [1, 4, 9, 16]
  ```
  - Change the line color to **red** and the line style to **dashed (`'--'`)**.
  - Add labels for both axes and a title.
"""

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [1, 4, 9, 16]
plt.plot(x,y,color='red',linestyle='--')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Graph')
plt.show()

"""### Exercise 8: Bar Chart of Monthly Sales
- **Task**: Create a bar chart to show monthly sales:
  - **Categories**: `['January', 'February', 'March']`
  - **Values**: `[300, 400, 350]`
  - Label the x-axis as **"Months"** and the y-axis as **"Sales"**.
  - Add a title: **"Monthly Sales"**.
"""

import matplotlib.pyplot as plt
Categories = ['January', 'February', 'March']
Values = [300, 400, 350]
plt.bar(Categories,Values)
plt.xlabel('Months')
plt.ylabel('Sales')
plt.title('Monthly Sales')
plt.show()

"""### Exercise 9: Scatter Plot for Test Scores
- **Task**: Create a scatter plot showing scores in two different subjects:
  ```python
  subject1_scores = [80, 85, 88, 90]
  subject2_scores = [70, 78, 85, 87]
  ```
  - Label the x-axis as **"Subject 1 Scores"** and the y-axis as **"Subject 2 Scores"**.
  - Add a title: **"Test Scores Comparison"**.
"""

import matplotlib.pyplot as plt
subject1_scores = [80, 85, 88, 90]
subject2_scores = [70, 78, 85, 87]
plt.scatter(subject1_scores,subject2_scores)
plt.xlabel('Subject 1 Scores')
plt.ylabel('Subject 2 Scores')
plt.title('Test Scores Comparison')
plt.show()

"""### Exercise 10: Simple Line Plot with Labels
- **Task**: Create a line plot using the following data:
  ```python
  x = [0, 1, 2, 3, 4]
  y = [0, 1, 4, 9, 16]
  ```
  - Label the x-axis as **"Input"** and the y-axis as **"Output"**.
  - Add a title: **"Input vs Output"**.
"""

import matplotlib.pyplot as plt
x = [0, 1, 2, 3, 4]
y = [0, 1, 4, 9, 16]
plt.plot(x,y)
plt.xlabel('Input')
plt.ylabel('Output')
plt.title('Input vs Output')
plt.show()